### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by azzlak** [nobody-html/BrowserCrash#1]
if i run the code in my website noting happens. I thing my Computer is too powerful

**Comment by nobody-html** [comment]
Maybe there is an issue with the setTimeout function (which I only inserted to make sure the page is completely loaded before the endless loop starts). Maybe try leaving the setTimeout thing out and just running the loop:
```js
while(true) {
    console.log(".");
}
```

**Comment by azzlak** [comment]
ooooook

**Comment by nobody-html** [comment]
You can also visit the [website](https://nobody-html.github.io/BrowserCrash/) for this repository and see if it works for you. The loop starts after 2 seconds after the website is loaded and should freeze the browser or at least slow it down.
